# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: app/proto/Products.proto for package 'rpc'

require "grpc"
require "app/proto/products_pb"

module Rpc
  module Products
    class Service
      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = "rpc.Products"

      rpc :GetProduct, ::Rpc::GetProductReq, ::Rpc::GetProductResp
      rpc :GetProducts, ::Rpc::GetProductsReq, stream(::Rpc::Product)
      rpc :CreateProducts, stream(::Rpc::Product), ::Rpc::CreateProductsResp
      rpc :CreateProductsInStream, stream(::Rpc::Product), stream(::Rpc::Product)
    end

    Stub = Service.rpc_stub_class
  end
end
